os:
  edit: "nvim"
  editAtLine: "{{editor}} +{{line}} -- {{filename}}"
  open: "open {{filename}}"
gui:
  showIcons: true
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
  showFileTree: false
git:
  pagers:
    - externalDiffCommand: difft --syntax-highlight=off --background=light --display=inline
